version: '2'
services:
   centerservice-1:
       container_name: centerservice-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       volumes:
       - ../target/CenterService.jar:/root/target/CenterService.jar