version: '2'
services:
   userservice-1:
       container_name: userservice-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       volumes:
       - ../target/UserService.jar:/root/target/UserService.jar