version: '2'
services:
   userservice:
       container_name: userservice-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "8002:8002"
       volumes:
       - ../target/UserService.jar:/root/target/UserService.jar