version: '2'
services:
   agentserivce:
       container_name: agentserivce-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "8009:8009"
       volumes:
       - ../target/AgentService.jar:/root/target/AgentService.jar