version: '2'
services:
   webserivce:
       container_name: webserivce-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "443:8443"
       volumes:
       - ../target/WebService.jar:/root/target/WebService.jar