spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    enabled: false
  jms:
    pub-sub-domain: true

jedis:
  pool:
    config:
      maxTotal: 100
      maxIdle: 20
      maxWaitMillis: 20000
    host: 127.0.0.1
    port: 3306

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: order-service

