version: '2'
services:
   centerservice:
       container_name: centerservice-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "8001:8001"
       volumes:
       - ../target/CenterService.jar:/root/target/CenterService.jar